import { WeatherCode } from "@/types";

export const weatherImages: Record<WeatherCode, string> = {
  0: 'clear_sky.svg',
  1: 'partly_cloudy.svg',
  2: 'partly_cloudy.svg',
  3: 'overcast.svg',
  45: 'fog.svg',
  48: 'fog.svg',
  51: 'drizzle.svg',
  53: 'drizzle.svg',
  55: 'drizzle.svg',
  56: 'freezing_rain.svg',
  57: 'freezing_rain.svg',
  61: 'rain.svg',
  63: 'rain.svg',
  65: 'rain.svg',
  66: 'freezing_rain.svg',
  67: 'freezing_rain.svg',
  71: 'snowfall.svg',
  73: 'snowfall.svg',
  75: 'snowfall.svg',
  77: 'snowfall.svg',
  80: 'rain_showers.svg',
  81: 'rain_showers.svg',
  82: 'rain_showers.svg',
  85: 'snowfall.svg',
  86: 'snowfall.svg',
  95: 'thunderstorm.svg',
  96: 'thunderstorm.svg',
  99: 'thunderstorm.svg',
};

export const weatherDescriptions: Record<WeatherCode, string> = {
  0: 'Clear sky',
  1: 'Partly cloudy',
  2: 'Partly cloudy',
  3: 'Overcast',
  45: 'Fog',
  48: 'Depositing rime fog',
  51: 'Light drizzle',
  53: 'Moderate drizzle',
  55: 'Dense drizzle',
  56: 'Light freezing drizzle',
  57: 'Dense freezing drizzle',
  61: 'Slight rain',
  63: 'Moderate rain',
  65: 'Heavy rain',
  66: 'Light freezing rain',
  67: 'Heavy freezing rain',
  71: 'Slight snowfall',
  73: 'Moderate snowfall',
  75: 'Heavy snowfall',
  77: 'Snow grains',
  80: 'Slight rain showers',
  81: 'Moderate rain showers',
  82: 'Violent rain showers',
  85: 'Slight snow showers',
  86: 'Heavy snow showers',
  95: 'Thunderstorm',
  96: 'Slight hail thunderstorm',
  99: 'Heavy hail thunderstorm',
};